spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-gb
    username: postgres
    password: 1556
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update